# Generated by Django 2.1.2 on 2019-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_status_resid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='resID',
            field=models.IntegerField(null=True),
        ),
    ]
