# Generated by Django 2.1.2 on 2019-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190222_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resID', models.IntegerField(null=True)),
                ('depDue', models.CharField(max_length=5, null=True)),
                ('depRec', models.CharField(max_length=5, null=True)),
                ('conSent', models.CharField(max_length=5, null=True)),
                ('conRec', models.CharField(max_length=5, null=True)),
                ('conRecDate', models.DateField(null=True)),
                ('cancelled', models.CharField(max_length=5, null=True)),
                ('payAmount', models.IntegerField(null=True)),
                ('paymentDue', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
