# Generated by Django 2.1.2 on 2019-02-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20190225_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmodel',
            name='resID',
        ),
    ]
