# Generated by Django 2.2b1 on 2019-03-01 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_remove_statusmodel_resid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='conRecDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
