# Generated by Django 2.2b1 on 2019-03-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20190228_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='conRecDate',
            field=models.DateField(null=True),
        ),
    ]
