# Generated by Django 2.2b1 on 2019-03-01 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_auto_20190228_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='conRecDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
