# Generated by Django 2.2b1 on 2019-03-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0012_auto_20190228_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='payAmount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
