# Generated by Django 2.1.2 on 2018-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviseReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=140)),
                ('lastName', models.CharField(max_length=140)),
                ('dateStart', models.DateField(null=True)),
                ('dateEnd', models.DateField(null=True)),
                ('status', models.CharField(max_length=24)),
                ('paymentDue', models.BooleanField(null=True)),
                ('attendence', models.IntegerField(null=True)),
            ],
        ),
    ]
