# Generated by Django 2.1.2 on 2019-01-27 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisereservation',
            name='attendence',
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='address1',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='address2',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='chapCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='district',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='level',
            field=models.CharField(default=django.utils.timezone.now, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='lunch',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='numChap',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='numStud',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='progCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='progType',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='schoolName',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='specProg',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='studCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='timeEnd',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='timeStart',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='zip',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
