# Generated by Django 2.1.2 on 2019-02-03 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190202_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisereservation',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='revisereservation',
            old_name='comments',
            new_name='interComm',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='chapCost',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='progLength',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='progType',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='specProg',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='studCost',
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='address2',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='ael',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='eP',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='gradeLevel',
            field=models.CharField(default=django.utils.timezone.now, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='handson',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='mission',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='otherProg',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='progComm',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='resID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='sayNo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='slowPay',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='summerCamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='tour',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='visCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
