# Generated by Django 2.1.2 on 2019-02-03 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190202_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisereservation',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
