# Generated by Django 2.1.2 on 2019-02-04 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_revisereservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisereservation',
            name='ael',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='eP',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='gradeLevel',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='handson',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='interComm',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='otherProg',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='progComm',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='resID',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='sayNo',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='slowPay',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='summerCamp',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='visCost',
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='chapCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='lastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='progType',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='specProg',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='studCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='status',
            field=models.CharField(max_length=24),
        ),
    ]
