# Generated by Django 2.1.2 on 2019-02-06 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20190204_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisereservation',
            name='chapCost',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='progType',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='specProg',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='studCost',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='title',
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='ael',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='eP',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='gradeLevel',
            field=models.CharField(default=django.utils.timezone.now, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='handson',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='interComm',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='mission',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='numTotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='otherProg',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='progComm',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='resID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='sayNo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='slowPay',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='summerCamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='tour',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='visCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='status',
            field=models.CharField(max_length=140),
        ),
    ]
