# Generated by Django 2.1.2 on 2019-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20190205_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisereservation',
            name='paymentDue',
            field=models.IntegerField(null=True),
        ),
    ]
