# Generated by Django 2.1.2 on 2019-02-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20190222_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisereservation',
            old_name='zip',
            new_name='zipCode',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='resID',
        ),
    ]
