# Generated by Django 2.1.2 on 2019-02-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20190225_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisereservation',
            name='handson',
        ),
        migrations.AddField(
            model_name='revisereservation',
            name='handsOn',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='address1',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='address2',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='ael',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='city',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='district',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='eP',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='email',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='gradeLevel',
            field=models.IntegerField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='interComm',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='level',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='location',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='mission',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='numChap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='numStud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='numTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='otherProg',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='paymentDue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='progComm',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='progCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='sayNo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='schoolName',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='slowPay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='state',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='status',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='summerCamp',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='tour',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='visCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='zipCode',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
