# Generated by Django 2.1.2 on 2019-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20190225_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisereservation',
            name='gradeLevel',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='zipCode',
            field=models.IntegerField(default=0),
        ),
    ]
