# Generated by Django 2.1.2 on 2019-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20190225_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisereservation',
            name='interComm',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='revisereservation',
            name='progComm',
            field=models.CharField(default='', max_length=140),
        ),
    ]
