# Generated by Django 2.1.2 on 2019-02-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20190225_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisereservation',
            name='district',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='sayNo',
        ),
        migrations.RemoveField(
            model_name='revisereservation',
            name='slowPay',
        ),
    ]
