# Generated by Django 2.1.2 on 2019-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_auto_20190225_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviseReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=140)),
                ('address1', models.CharField(max_length=140)),
                ('address2', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=140)),
                ('zip', models.CharField(max_length=140)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
                ('district', models.BooleanField(null=True)),
                ('dateStart', models.DateField(null=True)),
                ('dateEnd', models.DateField(null=True)),
                ('timeStart', models.TimeField(null=True)),
                ('timeEnd', models.TimeField(null=True)),
                ('lunch', models.BooleanField(null=True)),
                ('level', models.CharField(max_length=24)),
                ('gradeLevel', models.CharField(max_length=24)),
                ('ael', models.CharField(max_length=140)),
                ('mission', models.CharField(max_length=140)),
                ('tour', models.CharField(max_length=140)),
                ('handson', models.CharField(max_length=140)),
                ('eP', models.CharField(max_length=140)),
                ('summerCamp', models.CharField(max_length=140)),
                ('otherProg', models.CharField(max_length=140)),
                ('numStud', models.IntegerField(null=True)),
                ('numChap', models.IntegerField(null=True)),
                ('visCost', models.IntegerField(null=True)),
                ('progCost', models.IntegerField(null=True)),
                ('paymentDue', models.IntegerField(null=True)),
                ('interComm', models.CharField(max_length=140)),
                ('slowPay', models.BooleanField(null=True)),
                ('sayNo', models.BooleanField(null=True)),
                ('status', models.CharField(max_length=140)),
                ('progComm', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='reviseReservation',
        ),
    ]
