# Generated by Django 2.2b1 on 2019-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_auto_20190302_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisereservationmodel',
            name='dateEnd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='revisereservationmodel',
            name='dateStart',
            field=models.DateField(null=True),
        ),
    ]
