# Generated by Django 2.1.2 on 2019-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=140)),
                ('resID', models.IntegerField(null=True)),
                ('depDue', models.CharField(max_length=5)),
                ('depRec', models.CharField(max_length=5)),
                ('conSent', models.CharField(max_length=5)),
                ('conRec', models.CharField(max_length=5)),
                ('conRecDate', models.DateField(null=True)),
                ('cancelled', models.CharField(max_length=5)),
                ('payAmount', models.IntegerField(null=True)),
                ('paymentDue', models.IntegerField(null=True)),
            ],
        ),
    ]
