# Generated by Django 2.1.2 on 2019-02-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='resID',
        ),
        migrations.RemoveField(
            model_name='status',
            name='schoolName',
        ),
    ]
