# Generated by Django 2.1.2 on 2019-02-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190210_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
